global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape your FastAPI app (if it exports metrics)
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Your app
    metrics_path: '/metrics'