version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: pacer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    container_name: pacer-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src
      - ../examples:/app/examples
    command: uvicorn examples.simple_app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis-data: